name: Deploy Eureka Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar JDK y Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Build with Maven
        run: mvn clean package -DskipTests


      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


      - name: Build and push Docker image
        run: |
          docker build -t cafeytigrillo/eureka-server:latest .
          docker push cafeytigrillo/eureka-server:latest

     
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            docker pull cafeytigrillo/eureka-server:latest
            docker-compose up -d
            exit
          EOF
