name: Deploy Eureka Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout del código
        uses: actions/checkout@v3

      
      - name: Login en DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      
      - name: Construir y subir imagen
        run: |
          docker build -t cafeytigrillo/eureka-server:latest .
          docker push cafeytigrillo/eureka-server:latest

      
      - name: Desplegar en EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            docker pull cafeytigrillo/eureka-server:latest
            docker-compose up -d
            exit
          EOF
